name: Build for release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-for-ubuntu-and-windows:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0
        with:
          key: ${{matrix.os}}
          shared-key: release
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo test --verbose
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: elv${{github.ref_name}}${{runner.os}}-${{runner.arch}}
          path: target/release/elv

  build-for-macos-silicon:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0
        with:
          key: mac-silicon
          shared-key: release
      - name: Build
        run: |
          rustup target add aarch64-apple-darwin
          cargo build --release --verbose --target=aarch64-apple-darwin
      - name: Test
        run: cargo test --verbose
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: elv${{github.ref_name}}${{runner.os}}-silicon
          path: target/release/elv
