name: Build for release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build and archive the artifacts
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0
        with:
          key: ${{matrix.os}}
          shared-key: release
      - name: Add target
        run: rustup target add ${{matrix.target}}
      - name: Build
        run: cargo build --release --verbose --target=${{matrix.target}}
      - name: Test
        run: cargo test --verbose
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: elv-${{github.ref_name}}-${{matrix.target}}
          path: target/${{matrix.target}}/release/elv
